import Head from "next/head";
import {
  AiFillInstagram,
  AiFillLinkedin,
  AiFillGithub,
  AiOutlineWhatsApp,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import profil from "../public/profil.jpg";
import web from "../public/Web.png";
import mobile from "../public/Mobile.png";
import database from "../public/Database.png";
import Image from "next/image";
import web1 from "../public/AllFreshLaundry.png";
import web2 from "../public/LibManage.png";
import web3 from "../public/web3.png";
import web4 from "../public/Bloodmoon.png";
import web5 from "../public/apk-perpus.png";
import web6 from "../public/Grafkom.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Portofolio</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  CV
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Dimas Arya Nurhakim
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Software Developer
            </h3>
            <div className="mx-auto w-96 h-96 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image
              src={profil} />
            </div>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Mahasiswa Teknik Informatika UIN Sunan Gunung Djati Bandung angkatan 2022.
            </p>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Saya memiliki keahlian dalam pengembangan web menggunakan HTML, CSS, Java, JavaScript, dan PHP, serta familiar dengan 
              framework seperti Django, Laravel, React.js, dan Flutter. Di sisi pengelolaan database, saya familiar dengan MySQL, PostgreSQL, dan SQLite.
            </p>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Saya adalah seorang fast learner yang disiplin dalam manajemen waktu, pekerjaan, dan berkomitmen terhadap kualitas hasil kerja
            </p>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Keahlian</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Dalam perjalanan saya menjadi seorang proggramer, saya telah mendapat beberapa keahlian.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={web} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Web Develompent
              </h3>
              <p className="py-2">
                Membuat web dinamis dan rensponsif dan sesuai kebutuhan pengguna.
              </p>
              <h4 className="py-4 text-teal-600">Tools I Use</h4>
              <p className="text-gray-800 py-1">Laravel</p>
              <p className="text-gray-800 py-1">React</p>
              <p className="text-gray-800 py-1">Springboot</p>
              <p className="text-gray-800 py-1">Indesign</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={mobile} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Mobile Develompent
              </h3>
              <p className="py-2">
                Membuat aplikasi yang optimized dan mudah digunakan.
              </p>
              <h4 className="py-4 text-teal-600">Tools I Use</h4>
              <p className="text-gray-800 py-1">Flutter</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={database} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Database Management
              </h3>
              <p className="py-2">
                Mengelola Database Relasional
              </p>
              <h4 className="py-4 text-teal-600">Tools I Use</h4>
              <p className="text-gray-800 py-1">MySQL</p>
              <p className="text-gray-800 py-1">PostgreSQL</p>
              <p className="text-gray-800 py-1">SQLite</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Project List</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Saya telah mengerjakan beberapa proyek dalam bidang web, mobile dan juga game.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={273}
                height={526}
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web6}
              />
            </div>
          </div>
        </section>
        <section>
          <div>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://www.instagram.com/damisdamas/" target="_blank">
                <AiFillInstagram />
              </a>
              <a href="https://www.linkedin.com/in/dimas-noer-02ba65268/" target="_blank">
                <AiFillLinkedin />
              </a>
              <a href="https://github.com/Synnoer" target="_blank">
                <AiFillGithub />
              </a>
              <a href="https://wa.me/+6289670169478?" target="_blank">
                <AiOutlineWhatsApp/>
              </a>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
